### ISSUE TITLE
Ubuntu 14.04 - issue compiling - libsystemd

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/xde-menu#1]
Im install all libsystemd packages and always get error return 

configure: error: Package requirements (libsystemd) were not met:
No package 'libsystemd' found

Really needs a package of systemd? Systemd is Evil.

**Comment by bbidulock** [comment]
Wow.  I'm still building this program.  The configure dependencies were just copied over from [xde-ctools](/bbidulock/xde-ctools) repo (where this menu program first resided).  The commit bc73fa3 above addresses this, I believe.  No more systemd dependency.  (It is only needed for the xde-logout and xde-xlock functions in the [xde-ctools](/bbidulock/xde-ctools) package.)  I'm still building this program and have only tested the "menugen" function so far.  The GTK menu and traymenu I'm still working on.  You can try the equivalent "perl" package in the [xdg-traymenu](/bbidulock/xdg-traymenu) repository.
