### ISSUE TITLE
Creation of appmenu without the submenu "Window Managers"

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/xde-menu#2]
I generate the menu for icewm the command:
```
xde-menugen -w icewm -t gnome -0
```
Decided to remove the submenu "Window Managers":
```
$ xde-menugen -w icewm -t gnome -0 -s appmenu
Segmentation fault
```
Other options work:
```
xde-menugen -w icewm -t gnome -0 --style appmenu
xde-menugen -w icewm -t gnome -0 -l
```
but at the same time one more level of menu ("Applications") is added,
programs.autogen.diff:
```
0a1
> menu "Applications" /usr/share/icons/Adwaita/16x16/places/start-here.png {
103,108c104
<     menu "Window Managers" - {
<       restart "Restart" -
<       restart "Start Hackedbox" /usr/share/icons/Adwaita/16x16/apps/preferences-system-windows.png hackedbox
<       restart "Start JWM" /usr/share/icons/Adwaita/16x16/apps/preferences-system-windows.png jwm
<       restart "Start Openbox" /usr/share/pixmaps/openbox.png /usr/bin/openbox-session
<     }
---
> }
```

How to receive the menu from the first command, but without the submenu "Window Managers"?

**Comment by bbidulock** [comment]
Pushed a commit that fixes -s and -M short options (which require arguments but were set to not want them).
You could get rid of that easy with:

    xde-menu -G -w icewm -t gnome -0 --style appmenu | sed '/Window Manager/,/}/d'

It is text output after all.

**Comment by bbidulock** [comment]
You might consider adding the xdg-launch program https://github.com/bbidulock/xde-launch.  xde-menu will find it and use it to launch the application with full startup notification.  It can also handle launching other window managers.

**Comment by arsonoff** [comment]
Oh, other style: `xde-menugen -w icewm -t gnome -0 --style entries`
