### ISSUE TITLE
--menu, -M  not working.

### ISSUE THREAD

**Issue by Thyname** [bbidulock/xde-menu#4]
```
$ xde-menugen --wmname=icewm --format=icewm -t gnome -M all
free(): invalid pointer
Aborted (core dumped)
```
it can be worked around using --root-menu option and pointing directly to the desired menu file (for example /etc/xdg/menus/settings.menu).

**Comment by bbidulock** [comment]
Well, -M option doesn't crash anymore; however, I don't think that --menu=all is valid.  The following works:

    xde-menugen --wmname=icewm --format=icewm -t gnome -M applications

**Comment by bbidulock** [comment]
Please close this issue if it has been resolved to your satisfaction.

**Comment by Thyname** [comment]
In fact it doesn't crash any more but no matter what name I use after --menu= or -M (be it 'system' 'settings'or other), it always outputs a full applications menu.

But in practice, using --root-menu and pointing to the proper .menu file works just as expected.

I have here in ~/.icewm/menu
`separator
includeprog xde-menugen --wmname=icewm --format=icewm -t gnome -0 -s entries
separator
includeprog xde-menugen --wmname=icewm --format=icewm --root-menu /etc/xdg/menus/settings.menu -t gnome -0 -s entries
`

and I have a menu with nothing that shouldn't be there and nothing missing (I deliberately disable the 'window managers' menu as Icewm already has a restart entry and my other installed xsession, xfce4-session, I'm not interested in starting it from inside icewm).

**Comment by Thyname** [comment]
![Screenshot_2019-09-04_11-53-43](https://user-images.githubusercontent.com/30552880/64266264-b1231600-cf0a-11e9-8ee8-b1e865fd84e7.png)

**Comment by bbidulock** [comment]
I think that should work now: it was searching but not finding...  Thanks for pointing the way.
