### ISSUE TITLE
Package should not use obsolete m4 macros

### ISSUE THREAD

**Issue by tim77** [bbidulock/xde-menu#7]
> Package should not use obsolete m4 macros

This says `fedora-review` tool.

```
AutoTools: Obsoleted m4s found
------------------------------
  AC_PROG_LIBTOOL found in: xde-menu-0.10/configure.ac:87
```

**Comment by bbidulock** [comment]
Gone now.  Thank you.

**Comment by bbidulock** [comment]
Please close this issue if you consider it resolved.  Thank you.

**Comment by tim77** [comment]
Thank you @bbidulock !
0.11 build in [process](https://copr.fedorainfracloud.org/coprs/atim/xde-menu/build/1028557/).
I am trying to [push](https://bugzilla.redhat.com/show_bug.cgi?id=1748942) `xde-menu` in official repos...
